### ISSUE TITLE
10.5 Compatibility

### ISSUE THREAD

**Issue by azinsharaf** [nicogis/RemoveClassExtension#3]
hi,

The two icons are greyed out when I select FGDB or feature classes. I am using ArcGIS Desktop 10.5. Have you developed the 10.5 version?

Thanks,
Azin

**Comment by nicogis** [comment]
in https://github.com/nicogis/RemoveClassExtension/releases is compiled for 10.4 but you can use for 10.4 or superior so you can use for 10.5.
The buttons are enabled if you select in arccatalog a feature class because the click on button removes instance/class extension (if exists) on feature class selected.
You need select feature class in tab Contents ( not in catalog tree)
I have updated readme
